---
title: ""
author: "pz"
date: "`r Sys.Date()`"
output:
    html_document:
        toc: true
        toc_depth: 6
        toc_float: true
        code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=FALSE, cache.lazy = FALSE, message=FALSE, warning = FALSE)
```

```{r eval=TRUE, include=FALSE, cache=FALSE }
library(SingleCellExperiment);library(magrittr);
library(data.table); library(ggpubr) ; library(ggpmisc)
library(patchwork);library(ggplot2)
theme_set(theme_bw(base_size = 16))
library(ggsci)
library(ggpubr)
library(openxlsx)
library(ggrepel)
library(rrvgo)
library(dittoSeq)
library(ggsci)
```



```{r}
data_dir <- "/Users/pz/Desktop/work/czi-inflammation/pz/prepareFilesForCellXGene/"
sce <- readRDS(paste0(data_dir, "sce_allCells_MM_sampleIntegration_2022-04-29.rds"))
rownames(sce) <- scater::uniquifyFeatureNames(ID = rowData(sce)$ID, names = rowData(sce)$Symbol)
sce$lbl = sce$comb_label2
sce = sce[, which(sce$comb_label2 %in% grep("mixed",  unique(sce$comb_label2), value=T, invert=T))]
```

```{r}
library(scater)
plotReducedDim(sce, "UMAP", colour_by = "lbl", text_by="lbl")
```





```{r find_mouse_deg}
SPECIES="mm"
sct <- sce[,sce$lbl != "unassigned"]
mks_all_dr <- lapply(unique(as.character(sct$lbl)), function(CELLTYPE){
    ss <- sct[, as.character(sct$lbl) == CELLTYPE]
    ncol(ss) %>% print
    print(CELLTYPE)
    lapply(unique(ss$day), function(DAY){
        ss <- ss[, as.character(ss$day) %in% c(DAY)]
        print(ncol(ss))
        print(DAY)
            lapply(unique(as.character(ss$tissue)), function(TISSUE){ 
                ss <- ss[, as.character(ss$tissue) == TISSUE]
                ncol(ss) %>% print
                print(TISSUE)
                print(table(ss$surgery, ss$lbl, ss$day))
                if(  length(unique(ss$surgery)) > 1 & all(table(ss$lbl) > 50) ){
                    mks <- scran::findMarkers(ss, group = ss$surgery, lfc=0.25)[["sham"]]
                    mks$gene <- rownames(mks)
                    mks$comp <- paste(CELLTYPE, TISSUE, DAY, SPECIES, sep = ".")
                    mks$tissue <- TISSUE
                    mks$Day <- DAY
                    mks$Celltype <- CELLTYPE
                    return(as.data.table(mks))
                } %>% rbindlist}) %>% rbindlist }) %>% rbindlist }) %>% rbindlist

comps = unique(mks_all_dr$comp)
comps = gtools::mixedsort(comps)
mrks = lapply(comps, function(x) {
  subset(mks_all_dr, comp == x)
})
names(mrks) = comps
```



```{r, fig.width=12, fig.height=4.5}
df_sig = lapply(1:length(mrks), function(x){
  sub = mrks[[x]]
  data.frame(cluster=unique(sub$comp), 
             tissue = unique(sub$tissue), 
             Day = unique(sub$Day), 
             Celltype = unique(sub$Celltype), 
             "FDR<0.05" =  nrow(subset(sub, FDR < 0.05)), check.names=F)
}) %>% rbindlist()
df = reshape2::melt(df_sig)

library(dplyr)

df <- df %>%
  group_by(tissue, Celltype) %>%
  dplyr::filter(sum(value[Day == "d01" | Day == "d01" | Day == "d30"]) != 0)

ggplot(df, aes(x=Celltype, y=value, fill=Day)) + geom_bar(position="dodge", stat="identity")+ facet_wrap(~tissue, scales="free", ncol=5) + theme_classic() + theme(legend.position = "bottom") + xlab("") + ylab("Number of DEGs")  + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) + scale_fill_manual(values=c("#FFA500", "#00A4BF", "#FC3665")) + theme(strip.background = element_blank())
```



# Session Info

```{r session, message=FALSE, warning=FALSE, cache=FALSE,echo=FALSE, fig.width=10, fig.height=5.5, context="data"}
sessionInfo()
```
