---
title: "Dotplot from IPA results"
subtitle:  "FIG2 E"
author: "pz"
date: "1/30/2023; updated `r Sys.Date()`"
output:
    html_document:
        toc: true
        toc_depth: 6
        toc_float: true
        code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=FALSE, cache.lazy = FALSE, message=FALSE, warning = FALSE)
```

```{r eval=TRUE, include=FALSE, cache=FALSE }
library(ggplot2);library(openxlsx);library(magrittr);library(data.table);library("readxl")
theme_set(theme_bw(base_size = 16))
```

# E

Ratio/Overlap =  The ratio of analysis-ready genes in the dataset associated with a pathway or function


```{r, fig.width=10, fig.height=10}
data_dir <- "./FIG_2E_IPA_input/"
files = list.files(path=data_dir, pattern=".xls", full.names = T)
files = grep("Liver|Blood", files, invert=T, value=T)
ipa_res =   lapply(files, function(x){
  print(x)
    in.df = read_excel(x, skip=1, col_names=T)
  in.df$cls =  gsub(".*/", "", x) %>% gsub(".xls", "", .)
  in.df
}) %>%  rbindlist()
colnames(ipa_res) = make.names(colnames(ipa_res))
ipa_res = subset(ipa_res, X.log.p.value. > -log10(0.01))
ipa_res = subset(ipa_res, Ratio > 0.025)

# top 10 from each
ipa_pathways_of_interest =   lapply(files, function(x){
  print(x)
    in.df = read_excel(x, skip=1, col_names=T)
        colnames(in.df) = make.names(colnames(in.df))
     in.df = subset(in.df, X.log.p.value. > -log10(0.01) &  Ratio > 0.025)
    in.df = head(in.df, 10)
    in.df$cls =  gsub(".*/", "", x) %>% gsub(".xls", "", .)
  in.df
}) %>%  rbindlist()
colnames(ipa_pathways_of_interest) = make.names(colnames(ipa_pathways_of_interest))

poi = unique(ipa_pathways_of_interest$Ingenuity.Canonical.Pathways)
poi = poi[poi %in% ipa_res$Ingenuity.Canonical.Pathways]

ipa_res_sub = subset(ipa_res, Ingenuity.Canonical.Pathways %in% poi )
ipa_res_sub$cls = factor(ipa_res_sub$cls)
```




## Dotplot (width = 9)


```{r, fig.width=9, fig.height=8}
df = dcast(ipa_res_sub[,c("Ingenuity.Canonical.Pathways", "cls", "X.log.p.value.")], Ingenuity.Canonical.Pathways~cls) %>% as.data.frame()
row.names(df) = df$Ingenuity.Canonical.Pathways
df$Ingenuity.Canonical.Pathways = NULL
df[is.na(df)] = 0
p = pheatmap::pheatmap(df, cluster_cols = F, silent=T)
ipa_res_sub$Ingenuity.Canonical.Pathways = factor(ipa_res_sub$Ingenuity.Canonical.Pathways, levels= row.names(df[p$tree_row$order,]))

lvls = c("EIF2 Signaling","Coronavirus Pathogenesis Pathway","Regulation of eIF4 and p70S6K Signaling","mTOR Signaling","Antigen Presentation Pathway","Mitochondrial Dysfunction","Oxidative Phosphorylation","Production of Nitric Oxide and Reactive Oxygen Species in Macrophages","Fcγ Receptor-mediated Phagocytosis in Macrophages and Monocytes","Phagosome Formation","Clathrin-mediated Endocytosis Signaling","Opioid Signaling Pathway","Cardiac Hypertrophy Signaling","Colorectal Cancer Metastasis Signaling","Macrophage Alternative Activation Signaling Pathway","LXR/RXR Activation","Virus Entry via Endocytic Pathways","Acute Phase Response Signaling","CLEAR Signaling Pathway","HIF1α Signaling","Pulmonary Healing Signaling Pathway","Glycolysis I","Gluconeogenesis I","Tumor Microenvironment Pathway","Ferroptosis Signaling Pathway","Osteoarthritis Pathway","MSP-RON Signaling In Macrophages Pathway","Neuroinflammation Signaling Pathway","PD-1, PD-L1 cancer immunotherapy pathway","Iron homeostasis signaling pathway","Heme Biosynthesis II","Heme Biosynthesis from Uroporphyrinogen-III I","Hypoxia Signaling in the Cardiovascular System","Rapoport-Luebering Glycolytic Shunt","Tetrapyrrole Biosynthesis II","Agranulocyte Adhesion and Diapedesis","Granulocyte Adhesion and Diapedesis","Complement System","Phagosome Maturation","Caveolar-mediated Endocytosis Signaling","Actin Nucleation by ARP-WASP Complex","Hepatic Fibrosis Signaling Pathway","RAC Signaling","Leukocyte Extravasation Signaling","RHOGDI Signaling","Signaling by Rho Family GTPases")

ipa_res_sub$Ingenuity.Canonical.Pathways = factor(ipa_res_sub$Ingenuity.Canonical.Pathways, levels= lvls)

ggplot(ipa_res_sub, aes(x = cls, y = Ingenuity.Canonical.Pathways, size = X.log.p.value.)) + geom_point(aes(fill = z.score), pch = 21)   + scale_fill_gradient2(low = "blue", midpoint = 0, mid = "white", high = "red", name="activation\nz-score") + ylab(NULL) + ggtitle("") + DOSE::theme_dose(12) + scale_size_continuous(range = c(3, 8),name="-log(p-value)") + guides(size = guide_legend(order = 1), color = guide_colorbar(order = 2)) + xlab("") + theme(axis.text.x=element_text(angle = 45, hjust = 1, vjust = 1))
```



# Session Info

```{r session, message=FALSE, warning=FALSE, cache=FALSE,echo=FALSE, fig.width=10, fig.height=5.5, context="data"}
sessionInfo()
```
