---
title: "Score markers --  myeloid cells -- M0_k50_cl9.15k50"
subtitle: "zebrafish"
author: "pz"
date: "11/10/2022; updated `r Sys.Date()`"
output:
    html_document:
        toc: true
        toc_depth: 6
        toc_float: true
        code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=FALSE, cache.lazy = FALSE, message=FALSE, warning = FALSE)
```

```{r eval=TRUE, include=FALSE, cache=FALSE }
library(SingleCellExperiment);library(magrittr);
library(data.table)
library(patchwork);library(ggplot2)
theme_set(theme_bw(base_size = 16))
```



```{r}
data_dir <- "./"
sce <- readRDS(paste0(data_dir, "sce_ZF_sampleIntegration_2022-02-02_noCounts.rds"))
coldata <- readRDS("colData_ZF_withM0Only-and-EpiCardMix-Redone.rds")
reddim <- readRDS("reducedDimList_ZF_withM0Only-and-EpiCardMix-Redone.rds")

table(row.names( colData(sce)) == row.names(coldata))
table(row.names(reddim@listData$UMAP) == row.names(reducedDim(sce, "UMAP")))
colData(sce) = coldata
reducedDims(sce) = reddim
scm = sce
scm = scm[,!is.na(scm$M0_k50_cl9.15k50)]

rownames(scm) <- scater::uniquifyFeatureNames(ID = rowData(scm)$ID, names = rowData(scm)$Symbol)

cluster_cols = ABCutilities:::fx.get_palette_ABC("tableau20")[1:length(unique(scm$M0_k50_cl9.15k50))]
names(cluster_cols) <- sort(unique(scm$M0_k50_cl9.15k50))
```


```{r fig.height = 7.5, fig.width = 15}
p1 <- scABC2::plot_reducedDim_from_sce(scm, which_reddim = "UMAP_M0_k50_cl9.15",
    color_by = "M0_k50_cl9.15k50", set_color=TRUE) +
    theme(legend.position = "right")
p2 <- scABC2::plot_reducedDim_from_sce(scm, which_reddim = "UMAP_M0_k50_cl9.15",
    color_by = "Tissue", set_color=TRUE) +
    theme(legend.position = "right")
p1+p2
```


# scoreMarkers

```{r}
mrks <- scran::scoreMarkers(scm, group = scm$M0_k50_cl9.15k50, block = scm$Sample)
rdata = rowData(scm)

mrks_l = lapply(as.list(mrks), function(x){
  auc.only <- x[,grepl("mean.AUC|mean.logFC.cohen", colnames(x))]
  x = data.frame(gene=row.names(auc.only), auc.only)
  x = merge(x, rdata, by="row.names")
  x
})

mrks_l_filt = lapply(as.list(mrks), function(x){
  auc.only <- x[,grepl("mean.AUC|mean.logFC.cohen", colnames(x))]
  x = data.frame(gene=row.names(auc.only), auc.only)
  x= subset(x, mean.AUC > 0.6)
  x = merge(x, rdata, by="row.names")
  x
})
#openxlsx::write.xlsx(mrks_l, file = paste0(data_dir,"ZF_scoreMarkers_M0_k50_cl9.15k50_2022-11_auc_unfiltered.xlsx"))
#openxlsx::write.xlsx(mrks_l_filt, file = paste0(data_dir,"ZF_scoreMarkers_M0_k50_cl9.15k50_2022-11_auc_filtered_meanAUCgt0.6.xlsx"))
```


```{r}
df_sig = lapply(1:length(mrks), function(x){
  sub = mrks[[x]]
  data.frame(cluster=paste0("cls",x), 
             "mean.AUC>0.6" = nrow(subset(sub, mean.AUC > 0.6)),
             "mean.AUC>0.7" = nrow(subset(sub, mean.AUC > 0.7)), check.names=F)
}) %>% rbindlist()
df_df = reshape2::melt(df_sig)
cluster_cols_s = cluster_cols
names(cluster_cols_s) = paste0("cls", names(cluster_cols_s))
ggplot(df_df, aes(x=cluster, y=value, fill=cluster)) + geom_col() + facet_wrap(~variable, scales="free") + theme_bw() + theme(legend.position = "none") + xlab("") + ylab("Number of Marker Genes") + scale_fill_manual(values=cluster_cols_s) + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```


# ORT testing {.tabset}

using results from mean.AUC > 0.6


```{r eval=TRUE, fig.width=15, results='asis', fig.height=7}
rd <- rowData(scm) %>% as.data.frame %>% as.data.table

## universe of ENTREZ IDs
all.entrez <-  clusterProfiler::bitr(rownames(scm), 
    fromType="SYMBOL", toType="ENTREZID",
    OrgDb="org.Dr.eg.db") %>%  as.data.table


comp.list <- lapply(mrks, function(x){
  x = subset(x, mean.AUC > 0.6)
  symbs = rownames(x)
    ens <- rd[Symbol %in% symbs]$ID
    return(all.entrez[SYMBOL %in% symbs]$ENTREZID)
})
names(comp.list) <- paste0("cls", 1:length(mrks))

cat("\n\n##","GO BP", "\n\n")
cp.GO = clusterProfiler::compareCluster(comp.list, fun="enrichGO",  OrgDb = org.Dr.eg.db, ont="BP",pvalueCutoff = 1, qvalueCutoff=1, readable=TRUE)
cp.GO_df = as.data.frame(cp.GO)[,c("Cluster", "Description","p.adjust")]
cp.GO_df = cp.GO_df[order(cp.GO_df$p.adjust, decreasing = F),]

pl = lapply(sort(unique(cp.GO_df$Cluster)), function(x){
  sub = subset(cp.GO_df, Cluster == x)
  sub = sub[order(sub$p.adjust, decreasing = F),]
  sub = head(sub, 10)
  sub$negLog10 = -log10(sub$p.adjust)
  sub$Description = factor(sub$Description, levels=rev(sub$Description))
  ggplot(sub, aes(x=Description, y=negLog10, fill=Cluster)) + geom_col() + coord_flip()  +  theme_bw(base_size=10) + theme(legend.position = "none") + xlab("") + ylab("-log10(q)") + scale_fill_manual(values=cluster_cols_s) + geom_hline(yintercept = -log10(0.05), linetype="dashed")  + ggtitle(x, subtitle = "GO:BP") + scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 50))
})
patchwork::wrap_plots(pl, heights = 1, widths = 1, ncol = 3)

#openxlsx::write.xlsx(as.data.frame(cp.GO), file = paste0(data_dir,"ZF_ORT_scoreMarkers_M0_k50_cl9.15k50_2022-11_meanAUCgtqvalueCutoff_GOBP_unfiltered.xlsx"))
```



# Session Info

```{r session, message=FALSE, warning=FALSE, cache=FALSE,echo=FALSE, fig.width=10, fig.height=5.5, context="data"}
sessionInfo()
```
