---
title: ""
author: "pz"
date: "`r Sys.Date()`"
output:
    html_document:
        toc: true
        toc_depth: 6
        toc_float: true
        code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=FALSE, cache.lazy = FALSE, message=FALSE, warning = FALSE)
```

```{r eval=TRUE, include=FALSE, cache=FALSE }
library(SingleCellExperiment);library(magrittr);
library(data.table); library(ggpubr) ; library(ggpmisc)
library(patchwork);library(ggplot2)
theme_set(theme_bw(base_size = 16))
library(ggsci)
library(ggpubr)
library(openxlsx)
library(ggrepel)
library(rrvgo)
library(dittoSeq)
library(ggsci)

```



```{r}
data_dir <- "/Users/pz/Desktop/work/czi-inflammation/pz/combined/"
sce <- readRDS(paste0(data_dir, "sce_ZF_sampleIntegration_2022-02-02_noCounts.rds"))
rownames(sce) <- scater::uniquifyFeatureNames(ID = rowData(sce)$ID, names = rowData(sce)$Symbol)
cdata = colData(sce)
cdata$lbl = 'na'
cdata[cdata$cluster_k50 == "8",]$lbl  <- "Hep"
cdata[cdata$cluster_k50 == "13",]$lbl  <- "Hep"
cdata[cdata$cluster_k50 == "9",]$lbl  <- "Macro"
cdata[cdata$cluster_k50 == "15",]$lbl <- "Macro"
cdata[cdata$cluster_k50 == "1",]$lbl <- "CM"
cdata[cdata$cluster_k50 == "12",]$lbl <- "Cholangiocyte"
cdata[cdata$cluster_k50 == "16",]$lbl <- "Acinar"
cdata[cdata$cluster_k50 == "14",]$lbl <- "Throm"
cdata[cdata$cluster_k50 == "7",]$lbl <- "NK_T"
cdata[cdata$cluster_k50 == "2",]$lbl <- "Erthy"
cdata[cdata$cluster_k50 == "6",]$lbl <- "Erthy"
cdata[cdata$cluster_k50 == "10",]$lbl <- "Erthy"
cdata[cdata$cluster_k50 == "4",]$lbl <- "B"
cdata[cdata$cluster_k50 == "11",]$lbl <- "Neutrophil"
cdata[cdata$cluster_k50 == "3",]$lbl <- "HPC_HSC"
cdata[cdata$cluster_k50 == "5",]$lbl <- "mixed"
colData(sce) = cdata
```

```{r}
library(scater)
plotReducedDim(sce, "UMAP", colour_by = "lbl", text_by="lbl")
```





```{r find_fish_deg}
SPECIES="dr"
sce$repl <- gsub(".+-([12])$", "rep\\1", sce$Sample)
sct <- sce
mks_all_dr <- lapply(unique(as.character(sct$lbl)), function(CELLTYPE){
  ss <- sct[, as.character(sct$lbl) == CELLTYPE]
  ncol(ss) %>% print
  print(CELLTYPE)
  lapply(c("dpi1","dpi7"), function(DAY){
    ss <- ss[, as.character(ss$post.surgery) %in% c(DAY, "ctrl")]
    print(ncol(ss))
    print(DAY)
    lapply(unique(as.character(ss$Tissue)), function(TISSUE){ 
      ss <- ss[, as.character(ss$Tissue) == TISSUE]
      ncol(ss) %>% print
      print(TISSUE)
      print(table(ss$post.surgery, ss$lbl))
      if(length(unique(ss$post.surgery)) > 1 & all(table(ss$comb_condition) > 50)){
        mks <- scran::findMarkers(ss, group = ss$post.surgery, block=ss$repl)[[DAY]]
        mks$gene <- rownames(mks)
        mks$comp <- paste(CELLTYPE, TISSUE, DAY, SPECIES, sep = ".")
        mks$Tissue <- TISSUE
        mks$Day <- DAY
        mks$Celltype <- CELLTYPE
        return(as.data.table(mks))
      } %>% rbindlist}) %>% rbindlist }) %>% rbindlist }) %>% rbindlist

comps = unique(mks_all_dr$comp)
comps = gtools::mixedsort(comps)
mrks = lapply(comps, function(x) {
  subset(mks_all_dr, comp == x)
})
names(mrks) = comps
```



```{r, fig.width=12, fig.height=4.5}
df_sig <- lapply(1:length(mrks), function(x) {
  sub <- mrks[[x]]
  data.frame(
    cluster = unique(sub$comp),
    Tissue = unique(sub$Tissue),
    Day = unique(sub$Day),
    Celltype = unique(sub$Celltype),
    "FDR<0.05" = nrow(subset(sub, FDR < 0.05 & abs(summary.logFC) > 0.25)),
    check.names = FALSE
  )
}) %>% rbindlist()

df <- reshape2::melt(df_sig)

df <- df %>%
  group_by(Tissue, Celltype) %>%
  dplyr::filter(sum(value[Day == "dpi1" | Day == "dpi7"]) != 0)

df$Celltype <- factor(df$Celltype, levels = c("Macro", "Neutrophil", "B", "NK_T", "Hep", "Acinar", "Erthy", "Throm", "Cholangiocyte", "CM", "HPC_HSC", "mixed"))

ggplot(df, aes(x = Celltype, y = value, fill = Day)) +
  geom_bar(position = "dodge", stat = "identity") +
  facet_wrap(~Tissue, scales = "free", ncol = 4) +
  theme_classic() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  xlab("") +
  ylab("Number of DEGs") +
  scale_fill_manual(values = c("#FFA500", "#00A4BF")) +
  theme(strip.background = element_blank())
```



# Session Info

```{r session, message=FALSE, warning=FALSE, cache=FALSE,echo=FALSE, fig.width=10, fig.height=5.5, context="data"}
sessionInfo()
```
